<?php /* Smarty version 2.6.26, created on 2024-09-15 04:47:39
         compiled from common_adminbuttons.tpl */ ?>
<?php echo ''; ?><?php echo $this->_tpl_vars['bar']['htmlbegin']; ?><?php echo '<div class="adminbuttons'; ?><?php if ($this->_tpl_vars['bar']['class'] != ""): ?><?php echo ' '; ?><?php echo $this->_tpl_vars['bar']['class']; ?><?php echo ''; ?><?php endif; ?><?php echo '"'; ?><?php if ($this->_tpl_vars['bar']['style'] != ""): ?><?php echo ' style="'; ?><?php echo $this->_tpl_vars['bar']['style']; ?><?php echo '"'; ?><?php endif; ?><?php echo '>'; ?><?php if ($this->_tpl_vars['bar']['buttonbar_title'] != ""): ?><?php echo '<span class="buttonbar_title">'; ?><?php echo $this->_tpl_vars['bar']['buttonbar_title']; ?><?php echo '</span>'; ?><?php endif; ?><?php echo ''; ?><?php $_from = $this->_tpl_vars['bar']['buttons']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }$this->_foreach['adminbuttons_index'] = array('total' => count($_from), 'iteration' => 0);
if ($this->_foreach['adminbuttons_index']['total'] > 0):
    foreach ($_from as $this->_tpl_vars['button_name'] => $this->_tpl_vars['button']):
        $this->_foreach['adminbuttons_index']['iteration']++;
?><?php echo ''; ?><?php if (! ($this->_foreach['adminbuttons_index']['iteration'] <= 1)): ?><?php echo ''; ?><?php echo $this->_tpl_vars['bar']['buttons_separator']; ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php echo $this->_tpl_vars['button']['htmlbegin']; ?><?php echo '<'; ?><?php echo $this->_tpl_vars['button']['htmlelement']; ?><?php echo ''; ?><?php $_from = $this->_tpl_vars['button']['attrs']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }$this->_foreach['adminbuttonsattrs_index'] = array('total' => count($_from), 'iteration' => 0);
if ($this->_foreach['adminbuttonsattrs_index']['total'] > 0):
    foreach ($_from as $this->_tpl_vars['abattr_name'] => $this->_tpl_vars['abattr']):
        $this->_foreach['adminbuttonsattrs_index']['iteration']++;
?><?php echo ''; ?><?php if ($this->_tpl_vars['abattr'] != ""): ?><?php echo ' '; ?><?php echo $this->_tpl_vars['abattr_name']; ?><?php echo '="'; ?><?php echo $this->_tpl_vars['abattr']; ?><?php echo '"'; ?><?php endif; ?><?php echo ''; ?><?php endforeach; endif; unset($_from); ?><?php echo '>'; ?><?php echo $this->_tpl_vars['button']['html']; ?><?php echo '</'; ?><?php echo $this->_tpl_vars['button']['htmlelement']; ?><?php echo '>'; ?><?php echo $this->_tpl_vars['button']['htmlend']; ?><?php echo ''; ?><?php endforeach; endif; unset($_from); ?><?php echo '</div>'; ?><?php echo $this->_tpl_vars['bar']['htmlend']; ?><?php echo ''; ?>