<?php $_config_vars = array (
  'cl_body_bgcolor' => '#f0f0f0',
  'cl_body_text' => '#000000',
  'cl_body_link' => '#000080',
  'cl_body_vlink' => '#000080',
  'cl_body_alink' => '#000000',
  'cl_area_bgcolor' => '#ffffff',
  'cl_logobar_bgcolor' => '#b0c4de',
  'cl_copyright_bgcolor' => '#b0c4de',
  'cl_contentcaption_bgcolor' => '#b0c4de',
  'cl_contentbody_bgcolor' => '#F8F8F8',
  'cl_contentcaption_bgcolor_otherpanels' => '#b0c4de',
  'cl_contentbody_bgcolor_otherpanels' => '#FFFFFF',
  'cl_menucaption_bgcolor' => '#b0c4de',
  'cl_menubody_bgcolor' => '#FFFFFF',
  'cl_contenttable_bgcolor' => '#c9c9c9',
  'cl_admintabletitle_bgcolor' => '#b8b8b8',
); ?>